name: Cypress E2E
on:
  pull_request:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Copy ENV configuration for CI
        run: cp .env.ci .env
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:5000
          env: apiUrl=http://localhost:5000,baseUrl=http://localhost:5000
